name: portfolio
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_spinkit: "^4.1.2"
  path_provider: ^1.6.10
  smooth_page_indicator: ^0.1.5
  url_launcher: ^5.4.10
  google_fonts: ^1.1.0
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^4.0.5345

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - images/

